#### **NumPy Starts Here**

list onek slow but numpy onek fast karon ekhane fixed type use kora hoy....numpy te hocche mainly just binary te rekhe dicche data jekhane list e duniyar reference type,size,object type, object value shob rakhtese....as a result numpy onek fast.....tar upor numpy e contigupus memory ache...jekhane list hocche ekdom scattered ekta jinish.

SIMD Vector Processing  
Effective Cache Utilization  


In [2]:
import numpy as np

**The Basics**

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#get dimension
print(a.ndim)
print(b.ndim)

1
2


In [8]:
#get shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#get type
a.dtype

dtype('int64')

In [11]:
b.dtype

dtype('float64')

In [12]:
a.itemsize

8

In [13]:
b.itemsize

8

In [14]:
a.size

3

In [15]:
b.size

6

In [16]:
a.nbytes

24

In [17]:
b.nbytes

48

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
#get a specific element [r,c]
print(a[1,-3])

12


In [ ]:
#get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [22]:
#get a specific column
print(a[:,2])

[ 3 10]


In [23]:
#getting little more fancy  [startidx:endidx:stepsize]
print(a[0,1:-1:2])

[2 4 6]


In [24]:
a[1,5]=20
print(a)
a[:,2]=5
print(a)
a[:,2]=(1,2)
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**3-d example**

In [25]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
print(b[0,1,1])

4


In [27]:
print(b[:,1,:])

[[3 4]
 [7 8]]


In [29]:
b[:,1,:]=5
print(b)

[[[1 2]
  [5 5]]

 [[5 6]
  [5 5]]]


In [30]:
#all zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [33]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [35]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [36]:
#random decimal values
np.random.rand(4,2)

array([[0.69893707, 0.1809099 ],
       [0.81130057, 0.15873797],
       [0.70819836, 0.45960594],
       [0.84792432, 0.14034165]])

In [ ]:
#random integer values
np.random.randint(-4,7,size=(3,3)) # -4 theke 7(exclusive) er moddhe

array([[-4, -1,  0],
       [ 1, -1,  3],
       [-2, -2,  1]], dtype=int32)

In [38]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr=np.array([1,2,3])
ri=np.repeat(arr,3)#jekono element erpor repeat korche...so mot 3 bar kore
print(ri)

[1 1 1 2 2 2 3 3 3]


In [48]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [51]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying arrays!!!**

In [53]:
a=np.array([1,2,3])
print(a)
b=a #eta reference copy kore just...b te change korle a teo change hoye jabe
print(b)
c=a.copy() # evabe krle shallow copy hoy


[1 2 3]
[1 2 3]


### **Mathematics**

In [54]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [55]:
a+2

array([3, 4, 5, 6])

In [56]:
a-2

array([-1,  0,  1,  2])

In [57]:
a*2

array([2, 4, 6, 8])

In [58]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [59]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [60]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
np.sin(a)     #sin ber kore

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [62]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [63]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

**Linear Algebra**

In [66]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

c=np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [68]:
#determinant ber kora
c=np.identity(3)
print(np.linalg.det(c))

1.0


**Statistics**

In [75]:
stats=np.array([[1,2,19],[9,5,6]])
print(stats)

[[ 1  2 19]
 [ 9  5  6]]


In [ ]:
print(np.min(stats)) # overall ke min sheta ber kore dey
print(np.min(stats,axis=0)) # proti column e ke min sheta ber kore dey
print(np.min(stats,axis=1))#proti row te ke min sheta ber kore dey

1
[1 2 6]
[1 5]


same kahini gulo max er khetreo hoy

In [ ]:
#sum
print(np.sum(stats)) # overall ke ssum ber kore dey
print(np.sum(stats,axis=0)) # proti column er sum ber kore dey
print(np.sum(stats,axis=1))#proti row er sum ber kore dey

42
[10  7 25]
[22 20]


**Reorganizing Arrays**

In [80]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((4,2))
print(after)

after2=before.reshape((2,2,2))
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
#Vertical stack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v1,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [82]:
#Horizontal stack
h1=np.ones((2,3))
h2=np.zeros((2,2))
np.hstack([h1,h2,h1,h1])

array([[1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.]])

**Data from the txt**

In [84]:
hehe=np.genfromtxt('data.txt',delimiter=',')
print(hehe)
hehe2=hehe.astype('int32')
print(hehe2)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


**Boolean Masking and Advanced Indexing**

In [ ]:
hehe2[hehe2>50]  #just 50 er boro gula niye ekta toiri hoye jabe array

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
print(hehe2>50) #pura matrix print hobe but ke 50 er boro ke choto eta niye

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a[[1,2,8]] # index 1,2,8 er value niye banao notun array b
print(b)

[2 3 9]


In [90]:
print(np.any(hehe2>50))
print(np.any(hehe2>50,axis=0))
print(np.any(hehe2>50,axis=1)) #any hocche kono jekono ekta 50 r beshi holei puratar jonno true print hobe
print()
print(np.all(hehe2>50))
print(np.all(hehe2>50,axis=0))
print(np.all(hehe2>50,axis=1)) 

True
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[ True  True  True]

False
[False False False False  True False False False False False False False
 False False False False False False]
[False False False]


In [91]:
(~((hehe2>50)&(hehe<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [96]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[21,22,23,24,25]])
print(a)
print(a[2:4,0:2])
print(a[[0,1,2,3],[1,2,3,4]])
print(a[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [21 22 23 24 25]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [24 25]]
