**Python starts now**  
So amra python basics porbo first e  
numpy testing:

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([10, 20, 30])
C = A + b
D = A * C
column_means = np.mean(D, axis=0)

print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Broadcasted Addition (A + b):\n", C)
print("Element-wise Multiplication (A * C):\n", D)
print("Column-wise Means:\n", column_means)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector b:
 [10 20 30]
Broadcasted Addition (A + b):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Element-wise Multiplication (A * C):
 [[ 11  44  99]
 [ 56 125 216]
 [119 224 351]]
Column-wise Means:
 [ 62. 131. 222.]


some noob python code:

In [15]:
character_name="Saklain"
character_age=21
isMale=True #capital diye shuru true
print("Hello from "+character_name+" .Ki obostha shobar??")
print("His age is: "+str(character_age)) # ekhane just character_age dile hobe na....noob python....number ke string banate pare na nije....amader kore nite hobe.. str() eta diye
print(character_age) #but just eta print korte chaile string kora lagbe na
character_name="Abbi" #ebhabei modify kore yaaayyy
#java types er pray shob
phrase="Adventures Of Tintin"
print(phrase.upper())
print(phrase.lower())
print(phrase.isupper())#upper kina check kore shob
print(len(phrase))
print(phrase[3])
print(phrase.index("f"))#jeta khujtesi oita na thakle error dibe
print(phrase.index("Tintin"))# emon poora string dile mainly ora oi string er first character er index dey # exactly milte hobe with case tahole pabe nahoy to error
print(phrase.replace("Tintin","Saklain"))#ekta new string return kkore aager ta change hoyna
print(phrase)#tar mane eije replace korlam eta real string ke edit kore na

Hello from Saklain .Ki obostha shobar??
His age is: 21
21
ADVENTURES OF TINTIN
adventures of tintin
False
20
e
12
14
Adventures Of Saklain
Adventures Of Tintin


In [ ]:
print(3*4.5)
print(10%3)
my_num=-5
print(my_num)
print(abs(my_num))
print(pow(3,2))
print(pow(4,6))
print(max(4,6))
print(min(4,6))
print(round(3.7))
print(round(3.5))#upper e chole jay 

13.5
1
-5
5
9
4096
6
4
4
4


In [22]:
from math import *
my_num=-5
print(floor(3.7))
print(ceil(3.2))
print(sqrt(3))

3
4
1.7320508075688772


**get input from user:**

In [25]:
name=input("Enter your name")
age=input("Enter your age: ")
print("Hello "+name+"! You're "+age)

Hello Saklain! You're 21


In [ ]:
num1=input("Enter a number: ")
num2=input("Enter another number: ")
result=int(num1)+int(num2) #int e na nile era string concat kore dey lol #abar etay problem ache float input dile mara kheye error dibe codde....so amader uchit float e niye jawa shob kichu ke
print(result)

In [26]:
print("i have {nothing}")

i have {nothing}


**Lists**

In [35]:
siblings=["Saklain", "Abbi", "Tuba"]
    #        0        1       2 
    #       -3       -2      -1
print(siblings)
print(siblings[1])
print(siblings[-1]) #orrrrrrrrrrrrreeeeeeeehhhhh    negative index... pichon theke -1 theke shuru hoy
print(siblings[-3])
print(siblings[1:])#1 therke last porjonto print korbe
subjects=["Dsa", "oop", "math", "chem", "mecha"]
print(subjects[1:4]) #last jei index dibo oitar aag porjonto print korbe
subjects[2]="linear algebra"
print(subjects)

['Saklain', 'Abbi', 'Tuba']
Abbi
Tuba
Saklain
['Abbi', 'Tuba']
['oop', 'math', 'chem']
['Dsa', 'oop', 'linear algebra', 'chem', 'mecha']


In [ ]:
friends=["Saklain", "Ussop","akif" ,"mithun", "mufeed","akib","akib","sami"]
friends.append("shuvo")
print(friends)
friends.sort()
print(friends)
lucky_numers=[1,2,3,45,43,2,23,3234,234,234,234,2]
lucky_numers.sort()
print(lucky_numers)
friends.extend(lucky_numers)
print(friends)
print(friends.index("mithun"))
print(friends.count("akib"))
friends.remove(2)
print(friends)
#friends.sort() ekhane sort dewa jabe na karon str r int er moddhe to compare korte pare na python
print(friends)
friends.pop() #last element ke ber kore dey
print(friends)
friends2=friends.copy()
friends.clear()
print(friends)
print(friends2)



['Saklain', 'Ussop', 'akif', 'mithun', 'mufeed', 'akib', 'akib', 'shuvo']
['Saklain', 'Ussop', 'akib', 'akib', 'akif', 'mithun', 'mufeed', 'shuvo']
[1, 2, 2, 2, 3, 23, 43, 45, 234, 234, 234, 3234]
['Saklain', 'Ussop', 'akib', 'akib', 'akif', 'mithun', 'mufeed', 'shuvo', 1, 2, 2, 2, 3, 23, 43, 45, 234, 234, 234, 3234]
5
2
['Saklain', 'Ussop', 'akib', 'akib', 'akif', 'mithun', 'mufeed', 'shuvo', 1, 2, 2, 3, 23, 43, 45, 234, 234, 234, 3234]
['Saklain', 'Ussop', 'akib', 'akib', 'akif', 'mithun', 'mufeed', 'shuvo', 1, 2, 2, 3, 23, 43, 45, 234, 234, 234, 3234]
['Saklain', 'Ussop', 'akib', 'akib', 'akif', 'mithun', 'mufeed', 'shuvo', 1, 2, 2, 3, 23, 43, 45, 234, 234, 234]
[]
['Saklain', 'Ussop', 'akib', 'akib', 'akif', 'mithun', 'mufeed', 'shuvo', 1, 2, 2, 3, 23, 43, 45, 234, 234, 234]


**Tuples**

In [50]:
coordinates = (4,5) # tuples immutable hoy
#coordinates[1]=6 # change kora jayna
print(coordinates[1])


5


In [51]:
coordinatelist=[(4,5), (7,8), (9,10)]
print(coordinatelist)

[(4, 5), (7, 8), (9, 10)]


**Functions**

In [54]:
def say_hi():
    print("hello from function")

print("Top")
#now just call it
say_hi()
print("bottom")

Top
hello from function
bottom


In [56]:
def say_hi(name,age):
    print("Hello "+name+" , you're "+age)

say_hi("Saklain","21")

Hello Saklain , you're 21


using return keyword:

In [ ]:
def cube(num):
    return num*num*num
    print("hehe") # eta to return er pore

print(cube(2))
result = cube(4)
print(result)

8
64


**If statements**

In [64]:
is_male=True
is_tall=False
if is_male and is_tall:
    print("Hey boy")
elif is_male and not(is_tall):
    print("Shorty")
elif not is_male:
    print("tintin")
else:
    print("Who are you??")

Shorty


In [ ]:
def max_num(num1,num2,num3):
    if num1>=num2 and num1>=num3:
        return num1
    elif num2>=num3:
        return num2 # != etao ache btw
    else:
        return num3

print(max_num(100,7,9))

100


**Key-Value Pairs**

In [71]:
month_conversions={
    "Jan" : "January",
    "Feb" : "February",
    "Mar" : "March",
    "Apr" : "April",
    "May" : "May",
    "Jun" : "June",
    "Jul" : "July",
    "Aug" : "August",
    "Sep" : "September",
    "Oct" : "October",
    "Nov" : "November",
    "Dec" : "December"
}

print(month_conversions["Nov"])
print(month_conversions.get("Dec"))
print(month_conversions.get("Luv","not a valid key")) # na pele porer argument e ja pathaisi oita print korbe....r porer argument na dewa thakle none print korbe

November
December
not a valid key


**While loop**

In [73]:
i=1
while i<10:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9


In [74]:
secret_word="Tintin"
guess=""
while guess!=secret_word:
    guess=input("Enter your guess: ")
print("We got it!!!!")

We got it!!!!


**For Loops**

In [75]:
for letter in "Adventures":
    print(letter)


A
d
v
e
n
t
u
r
e
s


In [76]:
for friend in friends2:
    print(friend)

Saklain
Ussop
akib
akib
akif
mithun
mufeed
shuvo
1
2
2
3
23
43
45
234
234
234


In [77]:
for idx in range(10):
    print(idx)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for idx in range(3,10):           #from 3 to 10 not including 10
    print(idx)

3
4
5
6
7
8
9


In [79]:
for idx in range(len(siblings)):
    print(siblings[idx])

Saklain
Abbi
Tuba


**Exponenets**

In [ ]:
print(2**3)
print(2**5) #2^5 ber kore mainly

def raise_to_power(num, power):
    ans=1
    for idx in range(abs(power)):
        ans*=num
    if power >= 0:
        return ans
    else:
        return 1/ans

print(raise_to_power(2,5))

8
32
32


**2D Lists**

In [90]:
number_grid=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0]
]

print(number_grid[0][2])

for row in range(len(number_grid)):
    for col in range(len(number_grid[row])):
        print(number_grid[row][col],end=" ")
    print()

for row in number_grid:
    for col in row:
        print(col,end=" ")
print()

for row in number_grid:
    print(row)

3
1 2 3 
4 5 6 
7 8 9 
0 
1 2 3 4 5 6 7 8 9 0 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[0]


A translator:

In [93]:
def translate_word(phrase):
    translation=""
    for letter in phrase:
        if letter in "AEIOUaeiou":
            translation+="g"
        else:
            translation+=letter
    return translation

print(translate_word("To be or not to be... that is the question"))

Tg bg gr ngt tg bg... thgt gs thg qggstggn


**Exception Handling**

In [98]:
try:
    value=10/0
    number=int(input("Enter aa number"))
    print(number)
except ZeroDivisionError as err:
    print(err)
except ValueError:
    print("Invalid input")

division by zero


**Reading from file**

In [105]:
tintinFile=open("tintin.txt","r")
print(tintinFile.readable())
print(tintinFile.read())
tintinFile.seek(0)
print(tintinFile.readline())
tintinFile.seek(0)
print(tintinFile.readlines()[1])
tintinFile.close()
tintinFile=open("tintin.txt","a")
tintinFile.write("\nSami - 23")
tintinFile.close()


True
Saklain - 21
Mithun - 21
Akib - 20
Akif - 21
ussop - 59Sami - 23
Saklain - 21

Mithun - 21



Python e arekta file e lekha code just "import filename" diye import kora jay tahole amra just eta use korei onno file er func , variable use korte parbo...like filename.say_hi("Saklain") evabe.

**Classes and Objects**

In [111]:
class Student:
    def __init__(self,name,major,gpa,is_on_probation):
        self.name=name
        self.major=major
        self.gpa=gpa
        self.is_on_probation=is_on_probation

    def on_honor_roll(self):
        if self.gpa>=3.5:
            return True
        else:
            return False
        
class GoodStudent(Student):
    def can_create_something(self):
        print("He creates")
    
student1=Student("Saklain","Cse",4,False)
print(student1.name)
print(student1.major)
print(student1.on_honor_roll())

studentgood =GoodStudent("Mithun","cse",4,False)
studentgood.can_create_something()


Saklain
Cse
True
He creates
